name: Deploy kol.js
on:
  push:
    paths:
      - "packages/kol.js/package.json"
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Check publish status
        id: check
        run: |
          NEXT_VERSION=$(jq -r '.version' < packages/kol.js/package.json)
          STATUS=$(curl --write-out '%{http_code}\n' --head --silent --output /dev/null https://registry.npmjs.org/kol.js/$NEXT_VERSION)
          echo "status=$STATUS" >> "$GITHUB_OUTPUT"

      - name: Publish if necessary
        if: ${{ steps.check.outputs.status == '404' }}
        run: |
          yarn workspace kol.js install --immutable
          yarn workspace kol.js build
          yarn workspace kol.js npm publish
        env:
          STATUS: ${{ steps.check.outputs.status }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    